In [3]:
import numpy as np
import pandas as pd
docentes=pd.read_csv('Docentes_De_Planta.csv')

In [4]:
docentes.dtypes

Facultad               object
Programa Académico     object
TC                    float64
MT                      int64
TOTAL                   int64
PREGRADO              float64
ESPECIALIZACIÓN       float64
MAESTRÍA              float64
DOCTORADO             float64
TOTAL G                 int64
AUXILIAR              float64
ASISTENTE             float64
ASOCIADO              float64
TITULAR               float64
TOTAL GENERAL           int64
dtype: object

In [8]:
docentes=pd.read_csv('Docentes_De_Planta.csv',index_col='Facultad')
print(docentes)

                                                                            Programa Académico  \
Facultad
CIENCIAS AGROINDUSTRIALES                        INGENIERIA DE ALIMENTOS
NaN                                              TECNOLOGIA AGROINDUSTRIAL
NaN                                              TECNOLOGIA AGROPECUARIA
Total CIENCIAS AGROINDUSTRIALES                                                            NaN
CIENCIAS BASICAS Y TECNOLOGICAS                                           BIOLOGIA
NaN                                                                       FISICA
NaN                                                                       QUIMICA
NaN                                                 TECNOLOGIA EN INSTRUMENTACION ELECTRONICA
Total CIENCIAS BASICAS Y TECNOLOGICAS                                                      NaN
CIENCIAS DE LA SALUD                                                      ENFERMERIA
NaN                                                                       MEDICINA
NaN                                                           SEGURIDAD Y SALUD EN EL TRABAJO
Total CIENCIAS DE LA SALUD                                                                 NaN
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS            ADMINISTRACION DE NEGOCIOS  PRESENCIAL
NaN                                                                  ADMINISTRACION FINANCIERA
NaN                                                                       CONTADURIA
NaN                                                                                   ECONOMIA
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS                                                NaN
CIENCIAS HUMANAS Y BELLAS ARTES                                           ARTES VISUAL
NaN                                                 CIENCIAS DE LA INFORMACION Y LA DOC
NaN                                                 COMUNICACION SOCIAL Y PERIODISMO
NaN                                                                       FILOSOFIA
NaN                                                                       GERONTOLOGIA
NaN                                                                    TRABAJO SOCIAL
Total CIENCIAS HUMANAS Y BELLAS ARTES                                                      NaN
EDUCACION                                    LICENCIATURA DE BIOLOGIA Y EDUCACION AMBIENTAL...
NaN                                          LICENCIATURA EN EDUCACION FISICA Y DEPORTES   ...
NaN                                          LICENCIATURA EN ESPAÑOL Y LITERATURA          ...
NaN                                                           LICENCIATURA EN LENGUAS MODERNAS
NaN                                                           LICENCIATURA EN MATEMATICAS
NaN                                                         LICENCIATURA EN PEDAGOGIA INFANTIL
Total EDUCACION                                                                            NaN
INGENIERIA                                                                    INGENIERIA CIVIL
NaN                                                                 INGENIERIA DE SISTEMAS
NaN                                              INGENIERIA ELECTRONICA
NaN                                                 TECNOLOGIA EN OBRAS CIVILES
NaN                                                 TECNOLOGIA EN TOPOGRAFIA
Total INGENIERIA                                                                           NaN
Total general                                                                              NaN

                                               TC   MT  TOTAL  PREGRADO  \
Facultad
CIENCIAS AGROINDUSTRIALES                     NaN    8      8       NaN
NaN                                           NaN    2      2       NaN
NaN                                           NaN    1      1       NaN
Total CIENCIAS AGROINDUSTRIALES               NaN   11     11       NaN
CIENCIAS BASICAS Y TECNOLOGICAS               NaN    9      9       NaN
NaN                                           NaN   10     10       NaN
NaN                                           NaN   13     13       NaN
NaN                                           NaN   11     11       NaN
Total CIENCIAS BASICAS Y TECNOLOGICAS         NaN   43     43       NaN
CIENCIAS DE LA SALUD                          2.0    4      6       NaN
NaN                                          27.0   16     43       1.0
NaN                                           NaN    3      3       NaN
Total CIENCIAS DE LA SALUD                   29.0   23     52       1.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS         NaN    3      3       NaN
NaN                                           NaN    3      3       NaN
NaN                                           NaN   20     20       NaN
NaN                                           NaN    4      4       NaN
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS   NaN   30     30       NaN
CIENCIAS HUMANAS Y BELLAS ARTES               NaN    1      1       NaN
NaN                                           NaN    2      2       NaN
NaN                                           NaN    7      7       NaN
NaN                                           NaN    6      6       NaN
NaN                                           NaN    3      3       NaN
NaN                                           NaN    9      9       NaN
Total CIENCIAS HUMANAS Y BELLAS ARTES         NaN   28     28       NaN
EDUCACION                                     NaN   10     10       NaN
NaN                                           NaN    4      4       NaN
NaN                                           NaN    8      8       NaN
NaN                                           NaN   12     12       NaN
NaN                                           NaN   18     18       NaN
NaN                                           NaN    7      7       NaN
Total EDUCACION                               NaN   59     59       NaN
INGENIERIA                                    NaN   17     17       NaN
NaN                                           NaN   15     15       NaN
NaN                                           NaN   14     14       1.0
NaN                                           NaN    1      1       NaN
NaN                                           NaN    8      8       NaN
Total INGENIERIA                              NaN   55     55       1.0
Total general                                29.0  249    278       2.0

                                             ESPECIALIZACIÓN  MAESTRÍA  \
Facultad
CIENCIAS AGROINDUSTRIALES                                NaN       4.0
NaN                                                      NaN       1.0
NaN                                                      NaN       1.0
Total CIENCIAS AGROINDUSTRIALES                          NaN       6.0
CIENCIAS BASICAS Y TECNOLOGICAS                          NaN       3.0
NaN                                                      NaN       2.0
NaN                                                      NaN      10.0
NaN                                                      1.0       8.0
Total CIENCIAS BASICAS Y TECNOLOGICAS                    1.0      23.0
CIENCIAS DE LA SALUD                                     1.0       5.0
NaN                                                      NaN      34.0
NaN                                                      1.0       1.0
Total CIENCIAS DE LA SALUD                               2.0      40.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS                    NaN       3.0
NaN                                                      NaN       3.0
NaN                                                      2.0      17.0
NaN                                                      NaN       4.0
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS              2.0      27.0
CIENCIAS HUMANAS Y BELLAS ARTES                          NaN       1.0
NaN                                                      NaN       2.0
NaN                                                      NaN       4.0
NaN                                                      NaN       3.0
NaN                                                      NaN       3.0
NaN                                                      NaN       6.0
Total CIENCIAS HUMANAS Y BELLAS ARTES                    NaN      19.0
EDUCACION                                                NaN       5.0
NaN                                                      NaN       3.0
NaN                                                      NaN       6.0
NaN                                                      NaN       9.0
NaN                                                      NaN      11.0
NaN                                                      NaN       7.0
Total EDUCACION                                          NaN      41.0
INGENIERIA                                               1.0      15.0
NaN                                                      1.0       9.0
NaN                                                      1.0       7.0
NaN                                                      1.0       NaN
NaN                                                      2.0       5.0
Total INGENIERIA                                         6.0      36.0
Total general                                           11.0     192.0

                                             DOCTORADO  TOTAL G  AUXILIAR   \
Facultad
CIENCIAS AGROINDUSTRIALES                          4.0        8        NaN
NaN                                                1.0        2        NaN
NaN                                                NaN        1        NaN
Total CIENCIAS AGROINDUSTRIALES                    5.0       11        NaN
CIENCIAS BASICAS Y TECNOLOGICAS                    6.0        9        2.0
NaN                                                8.0       10        1.0
NaN                                                3.0       13        3.0
NaN                                                2.0       11        NaN
Total CIENCIAS BASICAS Y TECNOLOGICAS             19.0       43        6.0
CIENCIAS DE LA SALUD                               NaN        6        5.0
NaN                                                8.0       43       18.0
NaN                                                1.0        3        NaN
Total CIENCIAS DE LA SALUD                         9.0       52       23.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS              NaN        3        1.0
NaN                                                NaN        3        1.0
NaN                                                1.0       20        2.0
NaN                                                NaN        4        NaN
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS        1.0       30        4.0
CIENCIAS HUMANAS Y BELLAS ARTES                    NaN        1        1.0
NaN                                                NaN        2        NaN
NaN                                                3.0        7        1.0
NaN                                                3.0        6        1.0
NaN                                                NaN        3        NaN
NaN                                                3.0        9        3.0
Total CIENCIAS HUMANAS Y BELLAS ARTES              9.0       28        6.0
EDUCACION                                          5.0       10        NaN
NaN                                                1.0        4        NaN
NaN                                                2.0        8        1.0
NaN                                                3.0       12        7.0
NaN                                                7.0       18        NaN
NaN                                                NaN        7        NaN
Total EDUCACION                                   18.0       59        8.0
INGENIERIA                                         1.0       17        9.0
NaN                                                5.0       15        2.0
NaN                                                5.0       14        3.0
NaN                                                NaN        1        NaN
NaN                                                1.0        8        1.0
Total INGENIERIA                                  12.0       55       15.0
Total general                                     73.0      278       62.0

                                             ASISTENTE  ASOCIADO   TITULAR  \
Facultad
CIENCIAS AGROINDUSTRIALES                          4.0        3.0      1.0
NaN                                                1.0        1.0      NaN
NaN                                                1.0        NaN      NaN
Total CIENCIAS AGROINDUSTRIALES                    6.0        4.0      1.0
CIENCIAS BASICAS Y TECNOLOGICAS                    5.0        NaN      2.0
NaN                                                3.0        3.0      3.0
NaN                                                3.0        4.0      3.0
NaN                                                4.0        3.0      4.0
Total CIENCIAS BASICAS Y TECNOLOGICAS             15.0       10.0     12.0
CIENCIAS DE LA SALUD                               NaN        1.0      NaN
NaN                                               13.0        6.0      6.0
NaN                                                2.0        1.0      NaN
Total CIENCIAS DE LA SALUD                        15.0        8.0      6.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS              2.0        NaN      NaN
NaN                                                2.0        NaN      NaN
NaN                                                6.0        7.0      5.0
NaN                                                4.0        NaN      NaN
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS       14.0        7.0      5.0
CIENCIAS HUMANAS Y BELLAS ARTES                    NaN        NaN      NaN
NaN                                                1.0        1.0      NaN
NaN                                                3.0        3.0      NaN
NaN                                                1.0        2.0      2.0
NaN                                                3.0        NaN      NaN
NaN                                                3.0        2.0      1.0
Total CIENCIAS HUMANAS Y BELLAS ARTES             11.0        8.0      3.0
EDUCACION                                          7.0        1.0      2.0
NaN                                                1.0        3.0      NaN
NaN                                                5.0        1.0      1.0
NaN                                                2.0        2.0      1.0
NaN                                                6.0        7.0      5.0
NaN                                                3.0        3.0      1.0
Total EDUCACION                                   24.0       17.0     10.0
INGENIERIA                                         5.0        1.0      2.0
NaN                                                7.0        5.0      1.0
NaN                                                9.0        2.0      NaN
NaN                                                1.0        NaN      NaN
NaN                                                3.0        2.0      2.0
Total INGENIERIA                                  25.0       10.0      5.0
Total general                                    110.0       64.0     42.0

                                             TOTAL GENERAL
Facultad
CIENCIAS AGROINDUSTRIALES                                 8
NaN                                                       2
NaN                                                       1
Total CIENCIAS AGROINDUSTRIALES                          11
CIENCIAS BASICAS Y TECNOLOGICAS                           9
NaN                                                      10
NaN                                                      13
NaN                                                      11
Total CIENCIAS BASICAS Y TECNOLOGICAS                    43
CIENCIAS DE LA SALUD                                      6
NaN                                                      43
NaN                                                       3
Total CIENCIAS DE LA SALUD                               52
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS                     3
NaN                                                       3
NaN                                                      20
NaN                                                       4
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS              30
CIENCIAS HUMANAS Y BELLAS ARTES                           1
NaN                                                       2
NaN                                                       7
NaN                                                       6
NaN                                                       3
NaN                                                       9
Total CIENCIAS HUMANAS Y BELLAS ARTES                    28
EDUCACION                                                10
NaN                                                       4
NaN                                                       8
NaN                                                      12
NaN                                                      18
NaN                                                       7
Total EDUCACION                                          59
INGENIERIA                                               17
NaN                                                      15
NaN                                                      14
NaN                                                       1
NaN                                                       8
Total INGENIERIA                                         55
Total general                                           278

In [7]:
print(docentes['DOCTORADO'])

Facultad
CIENCIAS AGROINDUSTRIALES                       4.0
NaN                                             1.0
NaN                                             NaN
Total CIENCIAS AGROINDUSTRIALES                 5.0
CIENCIAS BASICAS Y TECNOLOGICAS                 6.0
NaN                                             8.0
NaN                                             3.0
NaN                                             2.0
Total CIENCIAS BASICAS Y TECNOLOGICAS          19.0
CIENCIAS DE LA SALUD                            NaN
NaN                                             8.0
NaN                                             1.0
Total CIENCIAS DE LA SALUD                      9.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS           NaN
NaN                                             NaN
NaN                                             1.0
NaN                                             NaN
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS     1.0
CIENCIAS HUMANAS Y BELLAS ARTES                 NaN
NaN                                             NaN
NaN                                             3.0
NaN                                             3.0
NaN                                             NaN
NaN                                             3.0
Total CIENCIAS HUMANAS Y BELLAS ARTES           9.0
EDUCACION                                       5.0
NaN                                             1.0
NaN                                             2.0
NaN                                             3.0
NaN                                             7.0
NaN                                             NaN
Total EDUCACION                                18.0
INGENIERIA                                      1.0
NaN                                             5.0
NaN                                             5.0
NaN                                             NaN
NaN                                             1.0
Total INGENIERIA                               12.0
Total general                                  73.0
Name: DOCTORADO, dtype: float64

In [9]:
docentes[['DOCTORADO','ASISTENTE','TITULAR']][:10]

                                       DOCTORADO  ASISTENTE  TITULAR
Facultad
CIENCIAS AGROINDUSTRIALES                    4.0        4.0      1.0
NaN                                          1.0        1.0      NaN
NaN                                          NaN        1.0      NaN
Total CIENCIAS AGROINDUSTRIALES              5.0        6.0      1.0
CIENCIAS BASICAS Y TECNOLOGICAS              6.0        5.0      2.0
NaN                                          8.0        3.0      3.0
NaN                                          3.0        3.0      3.0
NaN                                          2.0        4.0      4.0
Total CIENCIAS BASICAS Y TECNOLOGICAS       19.0       15.0     12.0
CIENCIAS DE LA SALUD                         NaN        NaN      NaN

In [10]:
docentes[['DOCTORADO','ASISTENTE','TITULAR']].head(10)

                                       DOCTORADO  ASISTENTE  TITULAR
Facultad
CIENCIAS AGROINDUSTRIALES                    4.0        4.0      1.0
NaN                                          1.0        1.0      NaN
NaN                                          NaN        1.0      NaN
Total CIENCIAS AGROINDUSTRIALES              5.0        6.0      1.0
CIENCIAS BASICAS Y TECNOLOGICAS              6.0        5.0      2.0
NaN                                          8.0        3.0      3.0
NaN                                          3.0        3.0      3.0
NaN                                          2.0        4.0      4.0
Total CIENCIAS BASICAS Y TECNOLOGICAS       19.0       15.0     12.0
CIENCIAS DE LA SALUD                         NaN        NaN      NaN

In [13]:
docentes.loc['CIENCIAS AGROINDUSTRIALES']

Programa Académico    INGENIERIA DE ALIMENTOS
TC                                                              NaN
MT                                                                8
TOTAL                                                             8
PREGRADO                                                        NaN
ESPECIALIZACIÓN                                                 NaN
MAESTRÍA                                                          4
DOCTORADO                                                         4
TOTAL G                                                           8
AUXILIAR                                                        NaN
ASISTENTE                                                         4
ASOCIADO                                                          3
TITULAR                                                           1
TOTAL GENERAL                                                     8
Name: CIENCIAS AGROINDUSTRIALES, dtype: object

In [15]:
docentes.loc['CIENCIAS BASICAS Y TECNOLOGICAS':'EDUCACION']

,Programa Académico,TC,MT,TOTAL,PREGRADO,ESPECIALIZACIÓN,MAESTRÍA,DOCTORADO,TOTAL G,AUXILIAR,ASISTENTE,ASOCIADO,TITULAR,TOTAL GENERAL
Facultad,,,,,,,,,,,,,,
CIENCIAS BASICAS Y TECNOLOGICAS,BIOLOGIA,NaN,9,9,NaN,NaN,3.0,6.0,9,2.0,5.0,NaN,2.0,9
NaN,FISICA,NaN,10,10,NaN,NaN,2.0,8.0,10,1.0,3.0,3.0,3.0,10
NaN,QUIMICA,NaN,13,13,NaN,NaN,10.0,3.0,13,3.0,3.0,4.0,3.0,13
NaN,TECNOLOGIA EN INSTRUMENTACION ELECTRONICA,NaN,11,11,NaN,1.0,8.0,2.0,11,NaN,4.0,3.0,4.0,11
Total CIENCIAS BASICAS Y TECNOLOGICAS,NaN,NaN,43,43,NaN,1.0,23.0,19.0,43,6.0,15.0,10.0,12.0,43
CIENCIAS DE LA SALUD,ENFERMERIA,2.0,4,6,NaN,1.0,5.0,NaN,6,5.0,NaN,1.0,NaN,6
NaN,MEDICINA,27.0,16,43,1.0,NaN,34.0,8.0,43,18.0,13.0,6.0,6.0,43
NaN,SEGURIDAD Y SALUD EN EL TRABAJO,NaN,3,3,NaN,1.0,1.0,1.0,3,NaN,2.0,1.0,NaN,3
Total CIENCIAS DE LA SALUD,NaN,29.0,23,52,1.0,2.0,40.0,9.0,52,23.0,15.0,8.0,6.0,52
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,ADMINISTRACION DE NEGOCIOS PRESENCIAL,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3
NaN,ADMINISTRACION FINANCIERA,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3
NaN,CONTADURIA,NaN,20,20,NaN,2.0,17.0,1.0,20,2.0,6.0,7.0,5.0,20
NaN,ECONOMIA,NaN,4,4,NaN,NaN,4.0,NaN,4,NaN,4.0,NaN,NaN,4
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,NaN,NaN,30,30,NaN,2.0,27.0,1.0,30,4.0,14.0,7.0,5.0,30
CIENCIAS HUMANAS Y BELLAS ARTES,ARTES VISUAL,NaN,1,1,NaN,NaN,1.0,NaN,1,1.0,NaN,NaN,NaN,1
NaN,CIENCIAS DE LA INFORMACION Y LA DOC,NaN,2,2,NaN,NaN,2.0,NaN,2,NaN,1.0,1.0,NaN,2
NaN,COMUNICACION SOCIAL Y PERIODISMO,NaN,7,7,NaN,NaN,4.0,3.0,7,1.0,3.0,3.0,NaN,7
NaN,FILOSOFIA,NaN,6,6,NaN,NaN,3.0,3.0,6,1.0,1.0,2.0,2.0,6
NaN,GERONTOLOGIA,NaN,3,3,NaN,NaN,3.0,NaN,3,NaN,3.0,NaN,NaN,3
NaN,TRABAJO SOCIAL,NaN,9,9,NaN,NaN,6.0,3.0,9,3.0,3.0,2.0,1.0,9
Total CIENCIAS HUMANAS Y BELLAS ARTES,NaN,NaN,28,28,NaN,NaN,19.0,9.0,28,6.0,11.0,8.0,3.0,28
EDUCACION,LICENCIATURA DE BIOLOGIA Y EDUCACION AMBIENTAL...,NaN,10,10,NaN,NaN,5.0,5.0,10,NaN,7.0,1.0,2.0,10

In [18]:
docentes.iloc[1:10]

,Programa Académico,TC,MT,TOTAL,PREGRADO,ESPECIALIZACIÓN,MAESTRÍA,DOCTORADO,TOTAL G,AUXILIAR,ASISTENTE,ASOCIADO,TITULAR,TOTAL GENERAL
Facultad,,,,,,,,,,,,,,
NaN,TECNOLOGIA AGROINDUSTRIAL,NaN,2,2,NaN,NaN,1.0,1.0,2,NaN,1.0,1.0,NaN,2
NaN,TECNOLOGIA AGROPECUARIA,NaN,1,1,NaN,NaN,1.0,NaN,1,NaN,1.0,NaN,NaN,1
Total CIENCIAS AGROINDUSTRIALES,NaN,NaN,11,11,NaN,NaN,6.0,5.0,11,NaN,6.0,4.0,1.0,11
CIENCIAS BASICAS Y TECNOLOGICAS,BIOLOGIA,NaN,9,9,NaN,NaN,3.0,6.0,9,2.0,5.0,NaN,2.0,9
NaN,FISICA,NaN,10,10,NaN,NaN,2.0,8.0,10,1.0,3.0,3.0,3.0,10
NaN,QUIMICA,NaN,13,13,NaN,NaN,10.0,3.0,13,3.0,3.0,4.0,3.0,13
NaN,TECNOLOGIA EN INSTRUMENTACION ELECTRONICA,NaN,11,11,NaN,1.0,8.0,2.0,11,NaN,4.0,3.0,4.0,11
Total CIENCIAS BASICAS Y TECNOLOGICAS,NaN,NaN,43,43,NaN,1.0,23.0,19.0,43,6.0,15.0,10.0,12.0,43
CIENCIAS DE LA SALUD,ENFERMERIA,2.0,4,6,NaN,1.0,5.0,NaN,6,5.0,NaN,1.0,NaN,6

In [21]:
docentes.iloc[[1,3,5],[1,3]]

                                 TC  TOTAL
Facultad
NaN                             NaN      2
Total CIENCIAS AGROINDUSTRIALES NaN     11
NaN                             NaN     10

In [22]:
docentes.iloc[[1,3,5],[1,3,4]]

                                 TC  TOTAL  PREGRADO
Facultad
NaN                             NaN      2       NaN
Total CIENCIAS AGROINDUSTRIALES NaN     11       NaN
NaN                             NaN     10       NaN

In [23]:
docentes[['ASISTENTE','TITULAR']][-15:]

                                       ASISTENTE  TITULAR
Facultad
Total CIENCIAS HUMANAS Y BELLAS ARTES       11.0      3.0
EDUCACION                                    7.0      2.0
NaN                                          1.0      NaN
NaN                                          5.0      1.0
NaN                                          2.0      1.0
NaN                                          6.0      5.0
NaN                                          3.0      1.0
Total EDUCACION                             24.0     10.0
INGENIERIA                                   5.0      2.0
NaN                                          7.0      1.0
NaN                                          9.0      NaN
NaN                                          1.0      NaN
NaN                                          3.0      2.0
Total INGENIERIA                            25.0      5.0
Total general                              110.0     42.0

In [24]:
docentes.plot(figsize=(10,15))

In [25]:
docentes['HONORIS CAUSA'] = range(39)

In [37]:
docentes.iloc[0:39]

,Programa Académico,TC,MT,TOTAL,PREGRADO,ESPECIALIZACIÓN,MAESTRÍA,DOCTORADO,TOTAL G,AUXILIAR,ASISTENTE,ASOCIADO,TITULAR,TOTAL GENERAL,HONORIS CAUSA
Facultad,,,,,,,,,,,,,,,
CIENCIAS AGROINDUSTRIALES,INGENIERIA DE ALIMENTOS,NaN,8,8,NaN,NaN,4.0,4.0,8,NaN,4.0,3.0,1.0,8,0
NaN,TECNOLOGIA AGROINDUSTRIAL,NaN,2,2,NaN,NaN,1.0,1.0,2,NaN,1.0,1.0,NaN,2,1
NaN,TECNOLOGIA AGROPECUARIA,NaN,1,1,NaN,NaN,1.0,NaN,1,NaN,1.0,NaN,NaN,1,2
Total CIENCIAS AGROINDUSTRIALES,NaN,NaN,11,11,NaN,NaN,6.0,5.0,11,NaN,6.0,4.0,1.0,11,3
CIENCIAS BASICAS Y TECNOLOGICAS,BIOLOGIA,NaN,9,9,NaN,NaN,3.0,6.0,9,2.0,5.0,NaN,2.0,9,4
NaN,FISICA,NaN,10,10,NaN,NaN,2.0,8.0,10,1.0,3.0,3.0,3.0,10,5
NaN,QUIMICA,NaN,13,13,NaN,NaN,10.0,3.0,13,3.0,3.0,4.0,3.0,13,6
NaN,TECNOLOGIA EN INSTRUMENTACION ELECTRONICA,NaN,11,11,NaN,1.0,8.0,2.0,11,NaN,4.0,3.0,4.0,11,7
Total CIENCIAS BASICAS Y TECNOLOGICAS,NaN,NaN,43,43,NaN,1.0,23.0,19.0,43,6.0,15.0,10.0,12.0,43,8
CIENCIAS DE LA SALUD,ENFERMERIA,2.0,4,6,NaN,1.0,5.0,NaN,6,5.0,NaN,1.0,NaN,6,9
NaN,MEDICINA,27.0,16,43,1.0,NaN,34.0,8.0,43,18.0,13.0,6.0,6.0,43,10
NaN,SEGURIDAD Y SALUD EN EL TRABAJO,NaN,3,3,NaN,1.0,1.0,1.0,3,NaN,2.0,1.0,NaN,3,11
Total CIENCIAS DE LA SALUD,NaN,29.0,23,52,1.0,2.0,40.0,9.0,52,23.0,15.0,8.0,6.0,52,12
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,ADMINISTRACION DE NEGOCIOS PRESENCIAL,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3,13
NaN,ADMINISTRACION FINANCIERA,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3,14
NaN,CONTADURIA,NaN,20,20,NaN,2.0,17.0,1.0,20,2.0,6.0,7.0,5.0,20,15
NaN,ECONOMIA,NaN,4,4,NaN,NaN,4.0,NaN,4,NaN,4.0,NaN,NaN,4,16
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,NaN,NaN,30,30,NaN,2.0,27.0,1.0,30,4.0,14.0,7.0,5.0,30,17
CIENCIAS HUMANAS Y BELLAS ARTES,ARTES VISUAL,NaN,1,1,NaN,NaN,1.0,NaN,1,1.0,NaN,NaN,NaN,1,18
NaN,CIENCIAS DE LA INFORMACION Y LA DOC,NaN,2,2,NaN,NaN,2.0,NaN,2,NaN,1.0,1.0,NaN,2,19
NaN,COMUNICACION SOCIAL Y PERIODISMO,NaN,7,7,NaN,NaN,4.0,3.0,7,1.0,3.0,3.0,NaN,7,20
NaN,FILOSOFIA,NaN,6,6,NaN,NaN,3.0,3.0,6,1.0,1.0,2.0,2.0,6,21
NaN,GERONTOLOGIA,NaN,3,3,NaN,NaN,3.0,NaN,3,NaN,3.0,NaN,NaN,3,22
NaN,TRABAJO SOCIAL,NaN,9,9,NaN,NaN,6.0,3.0,9,3.0,3.0,2.0,1.0,9,23
Total CIENCIAS HUMANAS Y BELLAS ARTES,NaN,NaN,28,28,NaN,NaN,19.0,9.0,28,6.0,11.0,8.0,3.0,28,24
EDUCACION,LICENCIATURA DE BIOLOGIA Y EDUCACION AMBIENTAL...,NaN,10,10,NaN,NaN,5.0,5.0,10,NaN,7.0,1.0,2.0,10,25
NaN,LICENCIATURA EN EDUCACION FISICA Y DEPORTES ...,NaN,4,4,NaN,NaN,3.0,1.0,4,NaN,1.0,3.0,NaN,4,26
NaN,LICENCIATURA EN ESPAÑOL Y LITERATURA ...,NaN,8,8,NaN,NaN,6.0,2.0,8,1.0,5.0,1.0,1.0,8,27
NaN,LICENCIATURA EN LENGUAS MODERNAS,NaN,12,12,NaN,NaN,9.0,3.0,12,7.0,2.0,2.0,1.0,12,28
NaN,LICENCIATURA EN MATEMATICAS,NaN,18,18,NaN,NaN,11.0,7.0,18,NaN,6.0,7.0,5.0,18,29
NaN,LICENCIATURA EN PEDAGOGIA INFANTIL,NaN,7,7,NaN,NaN,7.0,NaN,7,NaN,3.0,3.0,1.0,7,30
Total EDUCACION,NaN,NaN,59,59,NaN,NaN,41.0,18.0,59,8.0,24.0,17.0,10.0,59,31
INGENIERIA,INGENIERIA CIVIL,NaN,17,17,NaN,1.0,15.0,1.0,17,9.0,5.0,1.0,2.0,17,32
NaN,INGENIERIA DE SISTEMAS,NaN,15,15,NaN,1.0,9.0,5.0,15,2.0,7.0,5.0,1.0,15,33
NaN,INGENIERIA ELECTRONICA,NaN,14,14,1.0,1.0,7.0,5.0,14,3.0,9.0,2.0,NaN,14,34
NaN,TECNOLOGIA EN OBRAS CIVILES,NaN,1,1,NaN,1.0,NaN,NaN,1,NaN,1.0,NaN,NaN,1,35
NaN,TECNOLOGIA EN TOPOGRAFIA,NaN,8,8,NaN,2.0,5.0,1.0,8,1.0,3.0,2.0,2.0,8,36
Total INGENIERIA,NaN,NaN,55,55,1.0,6.0,36.0,12.0,55,15.0,25.0,10.0,5.0,55,37
Total general,NaN,29.0,249,278,2.0,11.0,192.0,73.0,278,62.0,110.0,64.0,42.0,278,38

In [38]:
docentes['HONORIS CAUSA'] = docentes['TITULAR']
docentes.iloc[0:39]

,Programa Académico,TC,MT,TOTAL,PREGRADO,ESPECIALIZACIÓN,MAESTRÍA,DOCTORADO,TOTAL G,AUXILIAR,ASISTENTE,ASOCIADO,TITULAR,TOTAL GENERAL,HONORIS CAUSA
Facultad,,,,,,,,,,,,,,,
CIENCIAS AGROINDUSTRIALES,INGENIERIA DE ALIMENTOS,NaN,8,8,NaN,NaN,4.0,4.0,8,NaN,4.0,3.0,1.0,8,1.0
NaN,TECNOLOGIA AGROINDUSTRIAL,NaN,2,2,NaN,NaN,1.0,1.0,2,NaN,1.0,1.0,NaN,2,NaN
NaN,TECNOLOGIA AGROPECUARIA,NaN,1,1,NaN,NaN,1.0,NaN,1,NaN,1.0,NaN,NaN,1,NaN
Total CIENCIAS AGROINDUSTRIALES,NaN,NaN,11,11,NaN,NaN,6.0,5.0,11,NaN,6.0,4.0,1.0,11,1.0
CIENCIAS BASICAS Y TECNOLOGICAS,BIOLOGIA,NaN,9,9,NaN,NaN,3.0,6.0,9,2.0,5.0,NaN,2.0,9,2.0
NaN,FISICA,NaN,10,10,NaN,NaN,2.0,8.0,10,1.0,3.0,3.0,3.0,10,3.0
NaN,QUIMICA,NaN,13,13,NaN,NaN,10.0,3.0,13,3.0,3.0,4.0,3.0,13,3.0
NaN,TECNOLOGIA EN INSTRUMENTACION ELECTRONICA,NaN,11,11,NaN,1.0,8.0,2.0,11,NaN,4.0,3.0,4.0,11,4.0
Total CIENCIAS BASICAS Y TECNOLOGICAS,NaN,NaN,43,43,NaN,1.0,23.0,19.0,43,6.0,15.0,10.0,12.0,43,12.0
CIENCIAS DE LA SALUD,ENFERMERIA,2.0,4,6,NaN,1.0,5.0,NaN,6,5.0,NaN,1.0,NaN,6,NaN
NaN,MEDICINA,27.0,16,43,1.0,NaN,34.0,8.0,43,18.0,13.0,6.0,6.0,43,6.0
NaN,SEGURIDAD Y SALUD EN EL TRABAJO,NaN,3,3,NaN,1.0,1.0,1.0,3,NaN,2.0,1.0,NaN,3,NaN
Total CIENCIAS DE LA SALUD,NaN,29.0,23,52,1.0,2.0,40.0,9.0,52,23.0,15.0,8.0,6.0,52,6.0
CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,ADMINISTRACION DE NEGOCIOS PRESENCIAL,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3,NaN
NaN,ADMINISTRACION FINANCIERA,NaN,3,3,NaN,NaN,3.0,NaN,3,1.0,2.0,NaN,NaN,3,NaN
NaN,CONTADURIA,NaN,20,20,NaN,2.0,17.0,1.0,20,2.0,6.0,7.0,5.0,20,5.0
NaN,ECONOMIA,NaN,4,4,NaN,NaN,4.0,NaN,4,NaN,4.0,NaN,NaN,4,NaN
Total CIENCIAS ECONOMICAS Y ADMINISTRATIVAS,NaN,NaN,30,30,NaN,2.0,27.0,1.0,30,4.0,14.0,7.0,5.0,30,5.0
CIENCIAS HUMANAS Y BELLAS ARTES,ARTES VISUAL,NaN,1,1,NaN,NaN,1.0,NaN,1,1.0,NaN,NaN,NaN,1,NaN
NaN,CIENCIAS DE LA INFORMACION Y LA DOC,NaN,2,2,NaN,NaN,2.0,NaN,2,NaN,1.0,1.0,NaN,2,NaN
NaN,COMUNICACION SOCIAL Y PERIODISMO,NaN,7,7,NaN,NaN,4.0,3.0,7,1.0,3.0,3.0,NaN,7,NaN
NaN,FILOSOFIA,NaN,6,6,NaN,NaN,3.0,3.0,6,1.0,1.0,2.0,2.0,6,2.0
NaN,GERONTOLOGIA,NaN,3,3,NaN,NaN,3.0,NaN,3,NaN,3.0,NaN,NaN,3,NaN
NaN,TRABAJO SOCIAL,NaN,9,9,NaN,NaN,6.0,3.0,9,3.0,3.0,2.0,1.0,9,1.0
Total CIENCIAS HUMANAS Y BELLAS ARTES,NaN,NaN,28,28,NaN,NaN,19.0,9.0,28,6.0,11.0,8.0,3.0,28,3.0
EDUCACION,LICENCIATURA DE BIOLOGIA Y EDUCACION AMBIENTAL...,NaN,10,10,NaN,NaN,5.0,5.0,10,NaN,7.0,1.0,2.0,10,2.0
NaN,LICENCIATURA EN EDUCACION FISICA Y DEPORTES ...,NaN,4,4,NaN,NaN,3.0,1.0,4,NaN,1.0,3.0,NaN,4,NaN
NaN,LICENCIATURA EN ESPAÑOL Y LITERATURA ...,NaN,8,8,NaN,NaN,6.0,2.0,8,1.0,5.0,1.0,1.0,8,1.0
NaN,LICENCIATURA EN LENGUAS MODERNAS,NaN,12,12,NaN,NaN,9.0,3.0,12,7.0,2.0,2.0,1.0,12,1.0
NaN,LICENCIATURA EN MATEMATICAS,NaN,18,18,NaN,NaN,11.0,7.0,18,NaN,6.0,7.0,5.0,18,5.0
NaN,LICENCIATURA EN PEDAGOGIA INFANTIL,NaN,7,7,NaN,NaN,7.0,NaN,7,NaN,3.0,3.0,1.0,7,1.0
Total EDUCACION,NaN,NaN,59,59,NaN,NaN,41.0,18.0,59,8.0,24.0,17.0,10.0,59,10.0
INGENIERIA,INGENIERIA CIVIL,NaN,17,17,NaN,1.0,15.0,1.0,17,9.0,5.0,1.0,2.0,17,2.0
NaN,INGENIERIA DE SISTEMAS,NaN,15,15,NaN,1.0,9.0,5.0,15,2.0,7.0,5.0,1.0,15,1.0
NaN,INGENIERIA ELECTRONICA,NaN,14,14,1.0,1.0,7.0,5.0,14,3.0,9.0,2.0,NaN,14,NaN
NaN,TECNOLOGIA EN OBRAS CIVILES,NaN,1,1,NaN,1.0,NaN,NaN,1,NaN,1.0,NaN,NaN,1,NaN
NaN,TECNOLOGIA EN TOPOGRAFIA,NaN,8,8,NaN,2.0,5.0,1.0,8,1.0,3.0,2.0,2.0,8,2.0
Total INGENIERIA,NaN,NaN,55,55,1.0,6.0,36.0,12.0,55,15.0,25.0,10.0,5.0,55,5.0
Total general,NaN,29.0,249,278,2.0,11.0,192.0,73.0,278,62.0,110.0,64.0,42.0,278,42.0